### ISSUE TITLE
Thank you for your tutorial. Can you help me with this problem?

### ISSUE THREAD

**Issue by ogbodotg** [FlorianPruemer/flutter_tutorials#2]
Hi,

Thank you very much for your audioplayer tutorial. I have learnt a lot.

But how do i populate the audioList with multiple data from firestore? 

My code only fetches a single song. How do i get all the songs in a collection into the List<Audio> audioList;

audioList.length only gets a single document

 audioList.add(
      Audio.network(widget.document.data()['song'],
          metas: Metas(
              title: widget.document.data()['songTitle'],
              artist: widget.document.data()['artistName'],
              image: MetasImage.network(widget.document.data()['songImage']))),

Thank you for your efforts.

**Comment by FlorianPruemer** [comment]
Hey! Unfortunately, fetching data from firestore is something I haven't really done yet, so I think I won't be much of a help here... In case the problem persists even after you are able to fetch all songs - so the problem has something to do with the audioplayer itself-  then I will be glad to help you out :)
